name: definetool
description: Define replacement tool to add implement define for all programming languages.
version: 1.0.0
# homepage: https://www.yzjlb.net

environment:
  sdk: '>=2.14.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: any
