name: face_plus CLI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            platform: arm
            output-name: definetool
          - os: macOS-latest
            output-name: definetool
          - os: windows-latest
            output-name: definetool.exe
    steps:
      - uses: actions/checkout@v4
      - uses: DanTup/gh-actions/setup-dart@master
      - name: platform
        run: file /bin/ls
      - name: install packages
        run: dart pub get
      - name: compile to native
        run: dart compile exe bin/definetool.dart -v -o ${{ matrix.output-name }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: definetool-${{ matrix.os }}
          path: definetool*
