name: face_plus CLI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            platform: arm
            output-name: linux_x64/definetool
          - os: macOS-latest
            output-name: macos_x64/definetool
          - os: windows-latest
            output-name: win_x64/definetool.exe
    steps:
      - uses: actions/checkout@v4
      - uses: DanTup/gh-actions/setup-dart@master
      - name: platform
        run: file /bin/ls
      - name: install packages
        run: dart pub get
      - name: make release/linux_x64 directory
        run: mkdir -p release/linux_x64
      - name: make release/macos_x64 directory
        run: mkdir -p release/macos_x64
      - name: make release/win_x64 directory
        run: mkdir -p release/win_x64
      - name: compile to native
        run: dart compile exe bin/definetool.dart -v -o release/${{ matrix.output-name }}
      - uses: actions/upload-artifact@v4
        with:
          name: face_plus
          path: release
